# -*- coding: utf-8 -*-
"""pincode problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AmLY4MjC6AMANBU-zMPhO5Tif--gwZk
"""

import re

def extract_pincode(address):

    pattern = r"\b[1-9][0-9]{2}\s?[0-9]{3}\b"

    match = re.search(pattern, address)

    if match:
        print(match.group().replace(" ", ""))  # Remove space if present
    else:
        print("-1")